//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYSANPHAM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SanPham
    {
        public int ID { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> GiaSP { get; set; }
        public Nullable<System.DateTime> NgaySX { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<int> IDDM { get; set; }
    }
}
